version: "3"
services:
# Redis 
  redis:
    container_name: redis_ru330
    build: 
      context: .
    image: 
      ${IMAGE_NAME}
    ports:
      - 6379:6379
    restart: unless-stopped    
    volumes:
          - ./conf:/usr/local/etc/redis:ro
          - ./data:/data:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

# Redis Insight
  redisinsight:
    container_name: redisinsight
    image: 
      redis/redisinsight:2.50
    ports:
      - 5540:5540
    restart: unless-stopped    
    volumes:
      - ./data:/data:rw
    depends_on:
      - redis 

# Redis Cli
  rediscli:
    container_name: rediscli
    image: 
      redisuniversity/ru330-base
    restart: unless-stopped    
    volumes:
          - ./data:/data:rw
    command: ["sleep", "365d"]
    depends_on:
      - redis 

#
# How to Keep Docker Container Running
# https://kodekloud.com/blog/keep-docker-container-running/
#

#
# EOF (2024/06/22)
#